"""Initial migration

Revision ID: aaa64d6f9aa0
Revises: 13c3e68b15e9
Create Date: 2025-06-15 23:40:15.565605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaa64d6f9aa0'
down_revision = '13c3e68b15e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
