"""添加简历表

Revision ID: d469e825d438
Revises: f32daf75434c
Create Date: 2025-07-03 23:17:06.433080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd469e825d438'
down_revision = 'f32daf75434c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_profiles_id', table_name='user_profiles')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('graduation_year', sa.VARCHAR(length=4), nullable=True),
    sa.Column('education', sa.VARCHAR(length=50), nullable=True),
    sa.Column('school', sa.VARCHAR(length=255), nullable=True),
    sa.Column('major_category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('major', sa.VARCHAR(length=255), nullable=True),
    sa.Column('target_position', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_user_profiles_id', 'user_profiles', ['id'], unique=False)
    # ### end Alembic commands ###
