"""add position tables

Revision ID: f32daf75434c
Revises: aaa64d6f9aa0
Create Date: 2025-06-18 19:17:55.548484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f32daf75434c'
down_revision = 'aaa64d6f9aa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
